### PR TITLE
Improve support for multiple cars

### LINKED ISSUE #182: Can not have two parallel Polestar IDs anymore
I have two cars and two separate polestar IDs. Until 1.7.2 this worked fine but in 1.7.3 the second car is no longer available.

image

image

I can see that the integration can successfully authenticate with the first entry (tried to anonymize the logs a bit):

```
2024-10-24 16:25:02.083 DEBUG (MainThread) [custom_components.polestar_api] async_setup_entry: <ConfigEntry entry_id=79a8864e79aa908b1b02d47ca4cb1dff version=1 domain=polestar_api title=Magnus Polestar state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>
<....>
2024-10-24 16:25:03.401 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.auth] {'data': {'getAuthToken': {'id_token': None, 'access_token': 'eyJhbGciOiJSUzI1NiIsImtpZCI6IlVVdkRibjM5QkZkcklhUWR0ZXhFVHdfYkxEa19SUzI1NiIsInBpLmF0bSI6ImwifQ.eyJzY29wZSI6IiIsImNsa
<......>
2024-10-24 16:25:05.053 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.polestar] {'data': {'getConsumerCarsV2': [{'vin': 'XXX', 'internalVehicleIdentifier': XXX, 'salesType': '82B', 'currentPlannedDeliveryDate': '2021-05-27', 'market': 'SE', 'originalMarket': 'SE', 'pno34': 'XXX', 'modelYear': '2021', 'registrationNo': 'TBA97R', 

```

but then it seems to reuse the same authentication for the second car and of course gets the same API response back:

```
2024-10-24 16:25:10.963 DEBUG (MainThread) [custom_components.polestar_api] async_setup_entry: <ConfigEntry entry_id=90f0c8caa13aa5f0c56c2bcd2f2392ba version=1 domain=polestar_api title=Emma Polestar state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>
<....>
2024-10-24 16:25:11.480 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.auth] {'data': {'getAuthToken': {'id_token': None, 'access_token': 'eyJhbGciOiJSUzI1NiIsImtpZCI6IlVVdkRibjM5QkZkcklhUWR0ZXhFVHdfYkxEa19SUzI1NiIsInBpLmF0bSI6ImwifQ.eyJzY29wZSI6IiIsImNsa
<......>
2024-10-24 16:25:12.473 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.polestar] {'data': {'getConsumerCarsV2': [{'vin': 'XXX', 'internalVehicleIdentifier': XXX', 'salesType': '82B', 'currentPlannedDeliveryDate': '2021-05-27', 'market': 'SE', 'originalMarket': 'SE', 'pno34': 'XXX', 'modelYear': '2021', 'registrationNo': 'TBA97R', 
```

### PR DESCRIPTION
**Pull request by jschlyter**
Split `Polestar` into one `PolestarCoordinator` per username and one `PolestarCar` per car. All calls to `PolestarApi` now requires a VIN and all data is cached by VIN.

Also allow specifying VIN when setting up integration. If specified, the integration will configure only the specified VIN only and ignore all other cars. Default is to import all cars.

Closes #182

### CODE REVIEW

**Review by leeyuentuen — APPROVED** [review]

**Comment by jschlyter** [comment]
The PR is still a draft – I'll mark it as ready for review when it's ready for review ;-)

**Comment by jschlyter** [comment]
Ping @magnushacker

**Comment by leeyuentuen** [comment]
we are moving back to use vin?

normally when we log in, we can fetch the vins.

**Comment by leeyuentuen** [comment]
lgtm

**Comment by magnushacker** [comment]
First try, without entering a VIN:
image
Log points to unhandled exception?

```
  File "/config/custom_components/polestar_api/config_flow.py", line 81, in async_step_user
    vin=user_input[CONF_VIN],
        ~~~~~~~~~~^^^^^^^^^^
KeyError: 'vin'

```
If I enter the VIN, the car shows up like normal. When I try to add the second entry using my wifes Polestar ID and the VIN on her car, I get "no_cars":

image

I get the same if I try my login and her VIN, which makes sense as it's not my car. I can however another duplicate entry with my polestar ID and my VIN, so at least the code for several entries works as it should.

**Comment by magnushacker** [comment]
Tried one more thing: I deleted the integration entries and added a new one using my wifes Polestar ID and her VIN, and I still get the no_cars message, so this is perhaps related to the polestar ID itself? 100% sure I have the correct VIN, as I copied it from the Polestar profile page.

**Comment by magnushacker** [comment]
One more test: added one entry with my wifes polestar ID and my VIN, and my car shows up. Tried the same thing with her VIN again and again the no_cars message. Still feels like the integration only works for the first car returned from the API?

**Comment by jschlyter** [comment]
> First try, without entering a VIN

Sorry about that, fixed in #188

**Pull request merged**
