### PR TITLE
Merge dev

### PR DESCRIPTION
**Pull request by jschlyter**
In preparation for next release, we'll merge dev into main. #165 should be merged first!

### CODE REVIEW

**Comment by jschlyter** [comment]
I've added Github topics, validate now succeeds

**Comment by jschlyter** [comment]
IMHO, we should consider removing `dev` and use `main` as the head branch for development.

**Comment by leeyuentuen** [comment]
> IMHO, we should consider removing `dev` and use `main` as the head branch for development.

i'm using dev for testing some stuffs.
so in the meantime there could be still have hotfixes in the main branch

**Comment by jschlyter** [comment]
> i'm using dev for testing some stuffs. so in the meantime there could be still have hotfixes in the main branch

Yes, that's one way to do it. I usually test stuff in dedicated feature branches and merge to main once ready. One can do pre-releases for the feature branch if required. The challenge with a dev branch is that PRs are usually targeted against main, which is then out of sync. So IMHO using a single head branch is easier for contributors. 

> is it ok to first create a beta release to hacs and see if there is any issue before release on main?

I suggest merge to main and do a pre-release from main. That will also help inclusion in HACS default list.

**Review by leeyuentuen — APPROVED** [review]

**Comment by jschlyter** [comment]
@leeyuentuen One more thing, if you do feature branches directly of main, the release notes are automatically generated based on merged PRs :-)

**Pull request merged**
